### PR TITLE
Fixed manmaeds bad code

### PR DESCRIPTION
**Pull request by UnRealDinnerbone**

### CODE REVIEW

**Comment by UnRealDinnerbone** [comment]
NEW JSON https://pastebin.com/raw/RXu1Cwki

**Review by manmaed — CHANGES_REQUESTED** [review]
Move URL to its own class like PRHats dose

**Review by manmaed — CHANGES_REQUESTED** [review]
Move all Hat Stuff to Own Class Like PRHats/HatData

**Comment by manmaed** [comment]
Fine Ill do it!

**Pull request merged**
